
import XCTest
import UIKit
@testable import ColorBlend

class ColorUtilsTests: XCTestCase {
    
    override func setUp() {
        super.setUp()
        // Put setup code here. This method is called before the invocation of each test method in the class.
    }
    
    override func tearDown() {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
        super.tearDown()
    }
    
    func testClosestMatch() {
        XCTAssertEqual(ColorName.closestMatch(UIColor.blackColor()), "Black")
        XCTAssertEqual(ColorName.closestMatch(UIColor.whiteColor()), "White")
        XCTAssertEqual(ColorName.closestMatch(UIColor.blueColor()),  "Blue")
        XCTAssertEqual(ColorName.closestMatch(UIColor.redColor()),   "Red")
        XCTAssertEqual(ColorName.closestMatch(UIColor.greenColor()), "Green")
        XCTAssertEqual(ColorName.closestMatch(UIColor.cyanColor()),  "Cyan")
        XCTAssertEqual(ColorName.closestMatch(UIColor.magentaColor()),  "Magenta")
        XCTAssertEqual(ColorName.closestMatch(UIColor.orangeColor()),  "Orange")
        XCTAssertEqual(ColorName.closestMatch(UIColor.brownColor()),  "Brown")
        XCTAssertEqual(ColorName.closestMatch(UIColor.lightGrayColor()),  "Light gray")
        XCTAssertEqual(ColorName.closestMatch(UIColor.darkGrayColor()),  "Dark gray")
        XCTAssertEqual(ColorName.closestMatch(UIColor.purpleColor()),  "Purple")
        
        XCTAssertEqual(ColorName.closestMatch(UIColor.init(red: 0, green: 0.0784313725490196, blue: 0.6588235294117647, alpha: 1.0)), "Zaffre")
        XCTAssertEqual(ColorName.closestMatch(UIColor.init(red: 0, green: 0.079, blue: 0.6588235294117647, alpha: 1.0)), "Zaffre")
    }
    
    func testNoDuplicateNames() {
        for spec in ColorName.ColorNames {
            let color = UIColor.init(red: spec.red, green: spec.green, blue: spec.blue, alpha: 1)
            XCTAssertEqual(ColorName.closestMatch(color), spec.name)
        }
    }
    
    func testHSVBlend() {
        XCTAssertEqual(ColorName.closestMatch(ColorUtils.hsvBlend([UIColor.redColor()])), "Red")
        XCTAssertEqual(ColorName.closestMatch(ColorUtils.hsvBlend([UIColor.blueColor()])), "Blue")
        XCTAssertEqual(ColorName.closestMatch(ColorUtils.hsvBlend([UIColor.redColor(), UIColor.blueColor()])), "Magenta")
        XCTAssertEqual(ColorName.closestMatch(ColorUtils.hsvBlend([UIColor.yellowColor(), UIColor.blueColor()])), "Spring green")
        XCTAssertEqual(ColorName.closestMatch(ColorUtils.hsvBlend([UIColor.redColor(), UIColor.redColor(), UIColor.greenColor()])), "Orange")
        

        let neutral = ColorUtils.hsvBlend([
            UIColor.blueColor(),
            UIColor.redColor(),
            UIColor.greenColor()
            ]);

        // This is nonintuitive, but due to the slight rounding this is what happens.
        XCTAssertEqual(ColorName.closestMatch(neutral), "Blue");
    }
    
    func colorWithHue(hueDegrees: Int) -> UIColor {
        return UIColor.init(hue: CGFloat(hueDegrees) / 360, saturation: 1, brightness: 1, alpha: 1)
    }
    
    func testClosestPrimaryHue() {
        func getClosestHue(hueDegrees: Int) -> Int {
            let color = colorWithHue(hueDegrees)
            return ColorUtils.getHueDegrees(ColorUtils.closestPrimaryColor(color))
        }
        
        XCTAssertEqual(getClosestHue(0), 360);
        XCTAssertEqual(getClosestHue(10), 360);
        XCTAssertEqual(getClosestHue(29), 360);
        XCTAssertEqual(getClosestHue(30), 60);
        XCTAssertEqual(getClosestHue(31), 60);
        XCTAssertEqual(getClosestHue(65), 60);
        XCTAssertEqual(getClosestHue(89), 60);
        XCTAssertEqual(getClosestHue(91), 120);
        XCTAssertEqual(getClosestHue(149), 120);
        XCTAssertEqual(getClosestHue(150), 180);
        XCTAssertEqual(getClosestHue(209), 180);
        XCTAssertEqual(getClosestHue(210), 240);
        XCTAssertEqual(getClosestHue(269), 240);
        XCTAssertEqual(getClosestHue(270), 300);
        XCTAssertEqual(getClosestHue(329), 300);
        XCTAssertEqual(getClosestHue(330), 360);
        XCTAssertEqual(getClosestHue(359), 360);
        XCTAssertEqual(getClosestHue(360), 360);
    }

    func describe(color: UIColor) -> String {
        var h: CGFloat = 0;
        var s: CGFloat = 0;
        var v: CGFloat = 0;
        color.getHue(&h, saturation: &s, brightness: &v, alpha: nil)
        
        let name = ColorName.closestMatch(color);
        let colorStr = "[\(name) \(String(Int(h * 360))) \(String(Int(s * 100))) \(String(Int(v * 100)))]";
        return colorStr;
    }
    
    func testHSVUnblend() {
        func S(colors: [UIColor]) -> String {
            var strs: [String] = [];
            
            for color in colors {
                strs.append(describe(color))
            }
            
            return strs.joinWithSeparator(" ");
        }
        
        XCTAssertEqual(S(ColorUtils.hsvUnblend(Constants.Palette.black)),
                       "[Black 0 0 0]")
        XCTAssertEqual(S(ColorUtils.hsvUnblend(Constants.Palette.white)),
                       "[White 0 0 100]")
        XCTAssertEqual(S(ColorUtils.hsvUnblend(Constants.Palette.gray)),
                       "[Black 0 0 0] [White 0 0 100] [White 0 0 100]")
        XCTAssertEqual(S(ColorUtils.hsvUnblend(Constants.Palette.red)),
                       "[Red 360 100 100]")
        XCTAssertEqual(S(ColorUtils.hsvUnblend(Constants.Palette.orange)),
                       "[Red 360 100 100] [Yellow 60 100 100]")
        XCTAssertEqual(S(ColorUtils.hsvUnblend(Constants.Palette.brown)),
                       "[Red 360 100 100] [Yellow 60 100 100] [White 0 0 100] [Black 0 0 0] [Black 0 0 0]")
        XCTAssertEqual(S(ColorUtils.hsvUnblend(Constants.Palette.pink)),
                       "[Magenta 300 100 100] [Magenta 300 100 100] [Red 360 100 100] [Red 360 100 100] [Red 360 100 100] [Red 360 100 100] [Red 360 100 100] [Red 360 100 100] [Red 360 100 100] [Red 360 100 100] [Red 360 100 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100] [White 0 0 100]")
    }
    
    func testHSVUnblendAllColors() {
        func getBlend(spec: ColorName) -> UIColor {
            let components = ColorUtils.hsvUnblend(spec.color)
            let blend = ColorUtils.hsvBlend(components)
            return blend;
        }

        func getColor(spec: ColorName) -> UIColor {
            return UIColor(red: spec.red, green: spec.green, blue: spec.blue, alpha: 1)
        }


        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Air Force blue")!)), "Air Force blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Alice blue")!)), "Alice blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Almond")!)), "Almond")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Amaranth")!)), "Amaranth")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Amber")!)), "Amber")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("American rose")!)), "American rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Amethyst")!)), "Amethyst")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Android Green")!)), "Android Green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Antique brass")!)), "Antique brass")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Antique fuchsia")!)), "Antique fuchsia")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Antique white")!)), "Antique white")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Apple green")!)), "Apple green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Apricot")!)), "Apricot")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Aquamarine")!)), "Aquamarine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Army green")!)), "Army green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Arylide yellow")!)), "Arylide yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ash grey")!)), "Ash grey")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Asparagus")!)), "Asparagus")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Atomic tangerine")!)), "Atomic tangerine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Auburn")!)), "Auburn")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Aureolin")!)), "Aureolin")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("AuroMetalSaurus")!)), "AuroMetalSaurus")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Awesome")!)), "Awesome")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Azure")!)), "Azure")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Azure mist/web")!)), "Azure mist/web")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Baby blue")!)), "Baby blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Baby blue eyes")!)), "Baby blue eyes")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Baby pink")!)), "Baby pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ball Blue")!)), "Ball Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Banana Mania")!)), "Banana Mania")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Banana yellow")!)), "Banana yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Battleship grey")!)), "Battleship grey")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bazaar")!)), "Bazaar")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Beau blue")!)), "Beau blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Beaver")!)), "Beaver")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Beige")!)), "Beige")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bisque")!)), "Bisque")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bistre")!)), "Bistre")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bittersweet")!)), "Bittersweet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Black")!)), "Black")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Blanched Almond")!)), "Blanched Almond")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bleu de France")!)), "Bleu de France")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Blizzard Blue")!)), "Blizzard Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Blond")!)), "Blond")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Blue")!)), "Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Blue Bell")!)), "Blue Bell")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Blue Gray")!)), "Blue Gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Blue-green")!)), "Blue-green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Blue-violet")!)), "Blue-violet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Blush")!)), "Blush")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bole")!)), "Bole")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bondi blue")!)), "Bondi blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Boston University Red")!)), "Boston University Red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Boysenberry")!)), "Boysenberry")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Brandeis blue")!)), "Brandeis blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Brass")!)), "Brass")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Brick red")!)), "Brick red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bright cerulean")!)), "Bright cerulean")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bright green")!)), "Bright green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bright lavender")!)), "Bright lavender")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bright maroon")!)), "Bright maroon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bright turquoise")!)), "Bright turquoise")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bright ube")!)), "Bright ube")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Brilliant lavender")!)), "Brilliant lavender")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Brilliant rose")!)), "Brilliant rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Brink pink")!)), "Brink pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("British racing green")!)), "British racing green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bronze")!)), "Bronze")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Brown")!)), "Brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bubble gum")!)), "Bubble gum")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bubbles")!)), "Bubbles")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Buff")!)), "Buff")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Bulgarian rose")!)), "Bulgarian rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Burgundy")!)), "Burgundy")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Burlywood")!)), "Burlywood")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Burnt orange")!)), "Burnt orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Burnt sienna")!)), "Burnt sienna")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Burnt umber")!)), "Burnt umber")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Byzantine")!)), "Byzantine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Byzantium")!)), "Byzantium")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cadet")!)), "Cadet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cadet blue")!)), "Cadet blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cadet grey")!)), "Cadet grey")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cadmium green")!)), "Cadmium green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cadmium orange")!)), "Cadmium orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cadmium red")!)), "Cadmium red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Café au lait")!)), "Café au lait")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Café noir")!)), "Café noir")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cal Poly Pomona green")!)), "Cal Poly Pomona green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cambridge Blue")!)), "Cambridge Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Camel")!)), "Camel")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Camouflage green")!)), "Camouflage green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Canary yellow")!)), "Canary yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Candy apple red")!)), "Candy apple red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Candy pink")!)), "Candy pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Caput mortuum")!)), "Caput mortuum")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cardinal")!)), "Cardinal")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Caribbean green")!)), "Caribbean green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Carmine pink")!)), "Carmine pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Carmine red")!)), "Carmine red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Carnation pink")!)), "Carnation pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Carnelian")!)), "Carnelian")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Carolina blue")!)), "Carolina blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Carrot orange")!)), "Carrot orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Celadon")!)), "Celadon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Celeste")!)), "Celeste")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Celestial blue")!)), "Celestial blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cerise")!)), "Cerise")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cerise pink")!)), "Cerise pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cerulean")!)), "Cerulean")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cerulean blue")!)), "Cerulean blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("CG Blue")!)), "CG Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("CG Red")!)), "CG Red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Chamoisee")!)), "Chamoisee")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Champagne")!)), "Champagne")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Charcoal")!)), "Charcoal")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Chartreuse")!)), "Chartreuse")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cherry blossom pink")!)), "Cherry blossom pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Chestnut")!)), "Chestnut")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Chocolate")!)), "Chocolate")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Chrome yellow")!)), "Chrome yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cinereous")!)), "Cinereous")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cinnabar")!)), "Cinnabar")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cinnamon")!)), "Cinnamon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Citrine")!)), "Citrine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Classic rose")!)), "Classic rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cobalt")!)), "Cobalt")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Coffee")!)), "Coffee")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Columbia blue")!)), "Columbia blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cool black")!)), "Cool black")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cool grey")!)), "Cool grey")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Copper")!)), "Copper")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Copper rose")!)), "Copper rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Coquelicot")!)), "Coquelicot")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Coral")!)), "Coral")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Coral pink")!)), "Coral pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Coral red")!)), "Coral red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cordovan")!)), "Cordovan")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Corn")!)), "Corn")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cornflower blue")!)), "Cornflower blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cornsilk")!)), "Cornsilk")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cosmic latte")!)), "Cosmic latte")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cotton candy")!)), "Cotton candy")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cream")!)), "Cream")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Crimson")!)), "Crimson")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Crimson glory")!)), "Crimson glory")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Cyan")!)), "Cyan")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Daffodil")!)), "Daffodil")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dandelion")!)), "Dandelion")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark blue")!)), "Dark blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark brown")!)), "Dark brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark byzantium")!)), "Dark byzantium")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark candy apple red")!)), "Dark candy apple red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark cerulean")!)), "Dark cerulean")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark chestnut")!)), "Dark chestnut")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark coral")!)), "Dark coral")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark cyan")!)), "Dark cyan")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark electric blue")!)), "Dark electric blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark goldenrod")!)), "Dark goldenrod")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark gray")!)), "Dark gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark green")!)), "Dark green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark jungle green")!)), "Dark jungle green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark khaki")!)), "Dark khaki")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark lavender")!)), "Dark lavender")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark magenta")!)), "Dark magenta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark midnight blue")!)), "Dark midnight blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark olive green")!)), "Dark olive green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark orange")!)), "Dark orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark orchid")!)), "Dark orchid")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark pastel blue")!)), "Dark pastel blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark pastel green")!)), "Dark pastel green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark pastel purple")!)), "Dark pastel purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark pastel red")!)), "Dark pastel red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark pink")!)), "Dark pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark powder blue")!)), "Dark powder blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark raspberry")!)), "Dark raspberry")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark red")!)), "Dark red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark salmon")!)), "Dark salmon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark scarlet")!)), "Dark scarlet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark sea green")!)), "Dark sea green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark sienna")!)), "Dark sienna")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark slate blue")!)), "Dark slate blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark slate gray")!)), "Dark slate gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark spring green")!)), "Dark spring green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark tan")!)), "Dark tan")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark tangerine")!)), "Dark tangerine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark terra cotta")!)), "Dark terra cotta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark turquoise")!)), "Dark turquoise")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dark violet")!)), "Dark violet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dartmouth green")!)), "Dartmouth green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Debian red")!)), "Debian red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep carmine")!)), "Deep carmine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep carmine pink")!)), "Deep carmine pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep carrot orange")!)), "Deep carrot orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep cerise")!)), "Deep cerise")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep chestnut")!)), "Deep chestnut")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep coffee")!)), "Deep coffee")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep fuchsia")!)), "Deep fuchsia")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep jungle green")!)), "Deep jungle green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep lilac")!)), "Deep lilac")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep magenta")!)), "Deep magenta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep peach")!)), "Deep peach")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep pink")!)), "Deep pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep saffron")!)), "Deep saffron")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Deep sky blue")!)), "Deep sky blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Denim")!)), "Denim")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Desert sand")!)), "Desert sand")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dim gray")!)), "Dim gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dodger blue")!)), "Dodger blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dogwood rose")!)), "Dogwood rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Dollar bill")!)), "Dollar bill")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Drab")!)), "Drab")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Duke blue")!)), "Duke blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Earth yellow")!)), "Earth yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Eggplant")!)), "Eggplant")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Eggshell")!)), "Eggshell")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Egyptian blue")!)), "Egyptian blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Electric blue")!)), "Electric blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Electric crimson")!)), "Electric crimson")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Electric indigo")!)), "Electric indigo")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Electric lime")!)), "Electric lime")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Electric purple")!)), "Electric purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Electric ultramarine")!)), "Electric ultramarine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Emerald")!)), "Emerald")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Eton blue")!)), "Eton blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Falu red")!)), "Falu red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Fandango")!)), "Fandango")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Fawn")!)), "Fawn")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Feldgrau")!)), "Feldgrau")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Fern green")!)), "Fern green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Field drab")!)), "Field drab")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Firebrick")!)), "Firebrick")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Fire engine red")!)), "Fire engine red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Flame")!)), "Flame")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Flamingo pink")!)), "Flamingo pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Flavescent")!)), "Flavescent")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Flax")!)), "Flax")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Floral white")!)), "Floral white")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Folly")!)), "Folly")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Forest green")!)), "Forest green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("French blue")!)), "French blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("French lilac")!)), "French lilac")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("French rose")!)), "French rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Fuchsia pink")!)), "Fuchsia pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Fulvous")!)), "Fulvous")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Fuzzy Wuzzy")!)), "Fuzzy Wuzzy")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Gainsboro")!)), "Gainsboro")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Gamboge")!)), "Gamboge")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ghost white")!)), "Ghost white")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ginger")!)), "Ginger")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Glaucous")!)), "Glaucous")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Glitter")!)), "Glitter")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Gold")!)), "Gold")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Golden brown")!)), "Golden brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Golden poppy")!)), "Golden poppy")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Golden yellow")!)), "Golden yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Goldenrod")!)), "Goldenrod")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Granny Smith Apple")!)), "Granny Smith Apple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Gray")!)), "Gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Gray-asparagus")!)), "Gray-asparagus")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Green")!)), "Green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Green-yellow")!)), "Green-yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Grullo")!)), "Grullo")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Halaya ube")!)), "Halaya ube")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Han blue")!)), "Han blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Han purple")!)), "Han purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Harlequin")!)), "Harlequin")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Harvard crimson")!)), "Harvard crimson")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Harvest Gold")!)), "Harvest Gold")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Heliotrope")!)), "Heliotrope")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Hollywood cerise")!)), "Hollywood cerise")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Honeydew")!)), "Honeydew")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Hooker's green")!)), "Hooker's green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Hot magenta")!)), "Hot magenta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Hot pink")!)), "Hot pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Hunter green")!)), "Hunter green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Icterine")!)), "Icterine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Inchworm")!)), "Inchworm")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("India green")!)), "India green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Indian yellow")!)), "Indian yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Indigo")!)), "Indigo")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("International Klein Blue")!)), "International Klein Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("International orange")!)), "International orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Iris")!)), "Iris")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Isabelline")!)), "Isabelline")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Islamic green")!)), "Islamic green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ivory")!)), "Ivory")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Jade")!)), "Jade")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Jasmine")!)), "Jasmine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Jasper")!)), "Jasper")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Jazzberry jam")!)), "Jazzberry jam")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("June bud")!)), "June bud")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Jungle green")!)), "Jungle green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Kelly green")!)), "Kelly green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Khaki")!)), "Khaki")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Khaki")!)), "Khaki")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("KU Crimson")!)), "KU Crimson")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("La Salle Green")!)), "La Salle Green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Languid lavender")!)), "Languid lavender")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lapis lazuli")!)), "Lapis lazuli")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Laser Lemon")!)), "Laser Lemon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Laurel green")!)), "Laurel green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lava")!)), "Lava")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lavender")!)), "Lavender")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lavender blush")!)), "Lavender blush")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lavender gray")!)), "Lavender gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lavender indigo")!)), "Lavender indigo")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lavender magenta")!)), "Lavender magenta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lavender mist")!)), "Lavender mist")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lavender pink")!)), "Lavender pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lavender purple")!)), "Lavender purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lavender rose")!)), "Lavender rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lawn green")!)), "Lawn green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lemon")!)), "Lemon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lemon chiffon")!)), "Lemon chiffon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light apricot")!)), "Light apricot")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light blue")!)), "Light blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light brown")!)), "Light brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light carmine pink")!)), "Light carmine pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light coral")!)), "Light coral")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light cornflower blue")!)), "Light cornflower blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light Crimson")!)), "Light Crimson")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light cyan")!)), "Light cyan")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light fuchsia pink")!)), "Light fuchsia pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light goldenrod yellow")!)), "Light goldenrod yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light gray")!)), "Light gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light green")!)), "Light green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light pastel purple")!)), "Light pastel purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light pink")!)), "Light pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light salmon")!)), "Light salmon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light salmon pink")!)), "Light salmon pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light sea green")!)), "Light sea green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light sky blue")!)), "Light sky blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light slate gray")!)), "Light slate gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light taupe")!)), "Light taupe")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light Thulian pink")!)), "Light Thulian pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Light yellow")!)), "Light yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lilac")!)), "Lilac")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lime")!)), "Lime")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lime green")!)), "Lime green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lincoln green")!)), "Lincoln green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Linen")!)), "Linen")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Liver")!)), "Liver")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Lust")!)), "Lust")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Magenta")!)), "Magenta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Magic mint")!)), "Magic mint")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Magnolia")!)), "Magnolia")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mahogany")!)), "Mahogany")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Majorelle Blue")!)), "Majorelle Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Malachite")!)), "Malachite")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Manatee")!)), "Manatee")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mango Tango")!)), "Mango Tango")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mantis")!)), "Mantis")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Maroon")!)), "Maroon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mauve")!)), "Mauve")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mauvelous")!)), "Mauvelous")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Maya blue")!)), "Maya blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Meat brown")!)), "Meat brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium aquamarine")!)), "Medium aquamarine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium blue")!)), "Medium blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium candy apple red")!)), "Medium candy apple red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium carmine")!)), "Medium carmine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium electric blue")!)), "Medium electric blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium jungle green")!)), "Medium jungle green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium lavender magenta")!)), "Medium lavender magenta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium orchid")!)), "Medium orchid")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium Persian blue")!)), "Medium Persian blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium purple")!)), "Medium purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium red-violet")!)), "Medium red-violet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium sea green")!)), "Medium sea green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium slate blue")!)), "Medium slate blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium spring bud")!)), "Medium spring bud")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium spring green")!)), "Medium spring green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium taupe")!)), "Medium taupe")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium teal blue")!)), "Medium teal blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Medium turquoise")!)), "Medium turquoise")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Melon")!)), "Melon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Midnight blue")!)), "Midnight blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Midnight green")!)), "Midnight green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mikado yellow")!)), "Mikado yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mint")!)), "Mint")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mint cream")!)), "Mint cream")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mint green")!)), "Mint green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Misty rose")!)), "Misty rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Moonstone blue")!)), "Moonstone blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mordant red 19")!)), "Mordant red 19")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Moss green")!)), "Moss green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mountain Meadow")!)), "Mountain Meadow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mountbatten pink")!)), "Mountbatten pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mulberry")!)), "Mulberry")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Mustard")!)), "Mustard")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Myrtle")!)), "Myrtle")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("MSU Green")!)), "MSU Green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Nadeshiko pink")!)), "Nadeshiko pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Napier green")!)), "Napier green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Naples yellow")!)), "Naples yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Navajo white")!)), "Navajo white")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Navy blue")!)), "Navy blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Neon Carrot")!)), "Neon Carrot")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Neon fuchsia")!)), "Neon fuchsia")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Neon green")!)), "Neon green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Non-photo blue")!)), "Non-photo blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("North Texas Green")!)), "North Texas Green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ocean Boat Blue")!)), "Ocean Boat Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ochre")!)), "Ochre")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Office green")!)), "Office green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Old gold")!)), "Old gold")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Old lace")!)), "Old lace")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Old lavender")!)), "Old lavender")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Old mauve")!)), "Old mauve")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Old rose")!)), "Old rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Olive")!)), "Olive")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Olive Drab")!)), "Olive Drab")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Olivine")!)), "Olivine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Onyx")!)), "Onyx")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Opera mauve")!)), "Opera mauve")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Orange")!)), "Orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Orange peel")!)), "Orange peel")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Orange-red")!)), "Orange-red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Orchid")!)), "Orchid")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Outer Space")!)), "Outer Space")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Outrageous Orange")!)), "Outrageous Orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Oxford Blue")!)), "Oxford Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pakistan green")!)), "Pakistan green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Palatinate blue")!)), "Palatinate blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Palatinate purple")!)), "Palatinate purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale blue")!)), "Pale blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale brown")!)), "Pale brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale cerulean")!)), "Pale cerulean")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale chestnut")!)), "Pale chestnut")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale copper")!)), "Pale copper")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale cornflower blue")!)), "Pale cornflower blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale gold")!)), "Pale gold")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale goldenrod")!)), "Pale goldenrod")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale green")!)), "Pale green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale lavender")!)), "Pale lavender")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale magenta")!)), "Pale magenta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale pink")!)), "Pale pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale robin egg blue")!)), "Pale robin egg blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale silver")!)), "Pale silver")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale spring bud")!)), "Pale spring bud")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale taupe")!)), "Pale taupe")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pale violet-red")!)), "Pale violet-red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pansy purple")!)), "Pansy purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Papaya whip")!)), "Papaya whip")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel blue")!)), "Pastel blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel brown")!)), "Pastel brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel gray")!)), "Pastel gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel green")!)), "Pastel green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel magenta")!)), "Pastel magenta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel orange")!)), "Pastel orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel pink")!)), "Pastel pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel purple")!)), "Pastel purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel red")!)), "Pastel red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel violet")!)), "Pastel violet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pastel yellow")!)), "Pastel yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Payne's grey")!)), "Payne's grey")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Peach")!)), "Peach")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Peach-orange")!)), "Peach-orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Peach puff")!)), "Peach puff")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Peach-yellow")!)), "Peach-yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pear")!)), "Pear")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pearl")!)), "Pearl")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pearl Aqua")!)), "Pearl Aqua")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Peridot")!)), "Peridot")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Periwinkle")!)), "Periwinkle")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Persian blue")!)), "Persian blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Persian green")!)), "Persian green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Persian indigo")!)), "Persian indigo")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Persian orange")!)), "Persian orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Persian pink")!)), "Persian pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Persian red")!)), "Persian red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Persian rose")!)), "Persian rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Phthalo blue")!)), "Phthalo blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Phthalo green")!)), "Phthalo green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Piggy pink")!)), "Piggy pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pine green")!)), "Pine green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pink")!)), "Pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pink pearl")!)), "Pink pearl")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pink Sherbet")!)), "Pink Sherbet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pistachio")!)), "Pistachio")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Platinum")!)), "Platinum")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Plum")!)), "Plum")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Portland Orange")!)), "Portland Orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Prune")!)), "Prune")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Prussian blue")!)), "Prussian blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Psychedelic purple")!)), "Psychedelic purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Puce")!)), "Puce")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Pumpkin")!)), "Pumpkin")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Purple")!)), "Purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Purple Heart")!)), "Purple Heart")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Purple mountain majesty")!)), "Purple mountain majesty")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Purple pizzazz")!)), "Purple pizzazz")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Purple taupe")!)), "Purple taupe")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Quartz")!)), "Quartz")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Radical Red")!)), "Radical Red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Raspberry")!)), "Raspberry")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Raspberry glace")!)), "Raspberry glace")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Raspberry pink")!)), "Raspberry pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Raspberry rose")!)), "Raspberry rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Raw umber")!)), "Raw umber")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Razzle dazzle rose")!)), "Razzle dazzle rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Razzmatazz")!)), "Razzmatazz")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Red")!)), "Red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Red-violet")!)), "Red-violet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Redwood")!)), "Redwood")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rich black")!)), "Rich black")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rich brilliant lavender")!)), "Rich brilliant lavender")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rich carmine")!)), "Rich carmine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rich electric blue")!)), "Rich electric blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rich lavender")!)), "Rich lavender")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rich lilac")!)), "Rich lilac")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rich maroon")!)), "Rich maroon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rifle green")!)), "Rifle green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Robin egg blue")!)), "Robin egg blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rose")!)), "Rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rose bonbon")!)), "Rose bonbon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rose ebony")!)), "Rose ebony")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rose gold")!)), "Rose gold")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rose madder")!)), "Rose madder")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rose pink")!)), "Rose pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rose taupe")!)), "Rose taupe")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rosewood")!)), "Rosewood")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rosso corsa")!)), "Rosso corsa")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rosy brown")!)), "Rosy brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Royal azure")!)), "Royal azure")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Royal blue")!)), "Royal blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Royal fuchsia")!)), "Royal fuchsia")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Royal purple")!)), "Royal purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ruby")!)), "Ruby")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ruddy")!)), "Ruddy")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ruddy brown")!)), "Ruddy brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ruddy pink")!)), "Ruddy pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rufous")!)), "Rufous")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Russet")!)), "Russet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Rust")!)), "Rust")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sacramento State green")!)), "Sacramento State green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Saddle brown")!)), "Saddle brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Safety orange")!)), "Safety orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Saffron")!)), "Saffron")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("St. Patrick's blue")!)), "St. Patrick's blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Salmon")!)), "Salmon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Salmon pink")!)), "Salmon pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sand")!)), "Sand")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sandstorm")!)), "Sandstorm")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sandy brown")!)), "Sandy brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sap green")!)), "Sap green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sapphire")!)), "Sapphire")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Satin sheen gold")!)), "Satin sheen gold")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Scarlet")!)), "Scarlet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("School bus yellow")!)), "School bus yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Screamin' Green")!)), "Screamin' Green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sea green")!)), "Sea green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Seal brown")!)), "Seal brown")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Seashell")!)), "Seashell")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sepia")!)), "Sepia")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Shadow")!)), "Shadow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Shamrock green")!)), "Shamrock green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Shocking pink")!)), "Shocking pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sienna")!)), "Sienna")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Silver")!)), "Silver")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sinopia")!)), "Sinopia")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Skobeloff")!)), "Skobeloff")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sky blue")!)), "Sky blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sky magenta")!)), "Sky magenta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Slate blue")!)), "Slate blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Slate gray")!)), "Slate gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Smokey topaz")!)), "Smokey topaz")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Smoky black")!)), "Smoky black")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Snow")!)), "Snow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Spiro Disco Ball")!)), "Spiro Disco Ball")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Splashed white")!)), "Splashed white")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Spring bud")!)), "Spring bud")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Spring green")!)), "Spring green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Steel blue")!)), "Steel blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Stizza")!)), "Stizza")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Straw")!)), "Straw")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Sunglow")!)), "Sunglow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tan")!)), "Tan")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tangelo")!)), "Tangelo")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tangerine")!)), "Tangerine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tangerine yellow")!)), "Tangerine yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Taupe")!)), "Taupe")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Taupe gray")!)), "Taupe gray")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tea green")!)), "Tea green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Teal")!)), "Teal")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Teal blue")!)), "Teal blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Teal green")!)), "Teal green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Terra cotta")!)), "Terra cotta")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Thistle")!)), "Thistle")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Thulian pink")!)), "Thulian pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tickle Me Pink")!)), "Tickle Me Pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tiffany Blue")!)), "Tiffany Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tiger's eye")!)), "Tiger's eye")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Timberwolf")!)), "Timberwolf")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Titanium yellow")!)), "Titanium yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tomato")!)), "Tomato")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Toolbox")!)), "Toolbox")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Topaz")!)), "Topaz")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tractor red")!)), "Tractor red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tropical rain forest")!)), "Tropical rain forest")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("True Blue")!)), "True Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tufts Blue")!)), "Tufts Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tumbleweed")!)), "Tumbleweed")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Turkish rose")!)), "Turkish rose")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Turquoise")!)), "Turquoise")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Turquoise blue")!)), "Turquoise blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Turquoise green")!)), "Turquoise green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tuscan red")!)), "Tuscan red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Twilight lavender")!)), "Twilight lavender")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Tyrian purple")!)), "Tyrian purple")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("UA blue")!)), "UA blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("UA red")!)), "UA red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ube")!)), "Ube")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("UCLA Blue")!)), "UCLA Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("UCLA Gold")!)), "UCLA Gold")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("UFO Green")!)), "UFO Green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ultramarine")!)), "Ultramarine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ultramarine blue")!)), "Ultramarine blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Ultra pink")!)), "Ultra pink")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Umber")!)), "Umber")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("United Nations blue")!)), "United Nations blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("University of California Gold")!)), "University of California Gold")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Unmellow Yellow")!)), "Unmellow Yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Upsdell red")!)), "Upsdell red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Urobilin")!)), "Urobilin")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Utah Crimson")!)), "Utah Crimson")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Vanilla")!)), "Vanilla")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Vegas gold")!)), "Vegas gold")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Venetian red")!)), "Venetian red")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Verdigris")!)), "Verdigris")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Veronica")!)), "Veronica")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Violet")!)), "Violet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Viridian")!)), "Viridian")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Vivid auburn")!)), "Vivid auburn")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Vivid burgundy")!)), "Vivid burgundy")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Vivid cerise")!)), "Vivid cerise")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Vivid tangerine")!)), "Vivid tangerine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Vivid violet")!)), "Vivid violet")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Warm black")!)), "Warm black")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Wenge")!)), "Wenge")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Wheat")!)), "Wheat")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("White")!)), "White")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("White smoke")!)), "White smoke")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Wild blue yonder")!)), "Wild blue yonder")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Wild Strawberry")!)), "Wild Strawberry")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Wild Watermelon")!)), "Wild Watermelon")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Wine")!)), "Wine")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Wisteria")!)), "Wisteria")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Xanadu")!)), "Xanadu")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Yale Blue")!)), "Yale Blue")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Yellow")!)), "Yellow")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Yellow-green")!)), "Yellow-green")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Yellow Orange")!)), "Yellow Orange")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Zaffre")!)), "Zaffre")
        XCTAssertEqual(ColorName.closestMatch(getBlend(ColorName.get("Zinnwaldite brown")!)), "Zinnwaldite brown")
    }

    
    func testMatchPerformance() {
        // This is an example of a performance test case.
        self.measureBlock {
            ColorName.closestMatch(UIColor.whiteColor())
        }
    }
    
}

